### ISSUE TITLE
data/pipeline/PATH doesnt exist

### ISSUE THREAD

**Issue by richteralexander** [richteralexander/plex#11]
I have downloaded Plex latest commit from Git today and moved all the content to D:/Dropbox/plex
To keep it simple I have created the same folder paths stated in the pipeline.yml  (C:\sandbox; D:\Dropbox\plex\1000; D:\Dropbox\plex\2000).  

I have kept the path stated on the /data/project/default/project.yml

Unfortunately no matter where I move the folders or what Path I put on the pipeline.yml I always get a "data/pipeline/PATH doesnt exist" when I try to run the win_maya.bat

D:\Dropbox\plex\data\exe\win_maya.bat
data/pipeline/PATH doesnt exist
Traceback (most recent call last):
  File "D:\Dropbox\plex\data\exe\\..\pipeline.py", line 195, in <module>
    Setup()
  File "D:\Dropbox\plex\data\exe\\..\pipeline.py", line 67, in __init__
    self.__call__()
  File "D:\Dropbox\plex\data\exe\\..\pipeline.py", line 149, in __call__
    LOG.debug('PATH:   {}'.format('[%s]' % ', '.join(map(str, sys.path))))
AttributeError: 'str' object has no attribute 'debug'

Thanks Rodrigo for the issues!

**Comment by richteralexander** [comment]
path mismatch between pipeline.yml and your current folder (plex != plex/2000)

v0.5.0 is more robust and kicks in some Maya basics
